---
# defaults/main.yml for kubernetes_client

## Dependency Management

kubernetes_dependency_package_names:
  - "tar"
  - "unzip"
kubernetes_dependency_package_state: "present"

## Global

kubernetes_binary_location: "/usr/local/bin"

## k9s

kubernetes_k9s_version: "v0.25.18"
kubernetes_k9s_state: "present"
kubernetes_k9s_url: "https://github.com/derailed/k9s/releases/download/{{ kubernetes_k9s_version }}/k9s_Linux_arm64.tar.gz"

## kubectl

kubernetes_kubectl_version: "v1.23.3"
kubernetes_kubectl_state: "present"
kubernetes_kubectl_url: "https://dl.k8s.io/release/{{ kubernetes_kubectl_version }}/bin/linux/amd64/kubectl"
kubernetes_kubectl_bash_completion_create: true

## kubectx

kubernetes_kubectx_version: "v0.9.4"
kubernetes_kubectx_state: "present"
kubernetes_kubectx_url: "https://github.com/ahmetb/kubectx/releases/download/v0.9.4/kubectx_v0.9.4_linux_x86_64.tar.gz"

## kubens

kubernetes_kubens_version: "v0.9.4"
kubernetes_kubens_state: "present"
kubernetes_kubens_url: "https://github.com/ahmetb/kubectx/releases/download/v0.9.4/kubens_v0.9.4_linux_x86_64.tar.gz"

## minikube

kubernetes_minikube_version: "latest"
kubernetes_minikube_state: "present"
kubernetes_minikube_url: "https://storage.googleapis.com/minikube/releases/{{ kubernetes_minikube_version }}/minikube-linux-amd64"
kubernetes_minikube_bash_completion_create: true
kubernetes_minikube_podman_sudo_enabled: true
kubernetes_minikube_podman_sudo_group: "wheel"
...
