---
# logitech/defaults/main.yml

logitech_package_names:
  - "solaar"
  - "libratbag-ratbagd"
logitech_package_state: "present"

logitech_flatpak_names: "org.freedesktop.Piper"
logitech_flatak_state: "present"
...
