---
# tasks/main.yml for kubernetes_client

## Dependency Management

- name: "Manage dependency Packages"
  ansible.builtin.package:
    name: "{{ kubernetes_dependency_package_names }}"
    state: "present"
  become: true
  tags:
    - "kubernetes"
    - "dependency"
    - "package"

- name: "Manage binary Path"
  ansible.builtin.file:
    name: "{{ kubernetes_binary_location }}"
    state: "directory"
  become: true
  tags:
    - "kubernetes"
    - "dependency"
    - "binary"
    - "package"

## Import Tasks

- name: "Import kubectl Tasks"
  ansible.builtin.import_tasks: "kubectl.yml"

- name: "Import kubectx Tasks"
  ansible.builtin.import_tasks: "kubectx.yml"

- name: "Import kubens Tasks"
  ansible.builtin.import_tasks: "kubens.yml"

- name: "Import k9s Tasks"
  ansible.builtin.import_tasks: "k9s.yml"

- name: "Import minikube Tasks"
  ansible.builtin.import_tasks: "minikube.yml"
...
