---
# tasks/main.yml for bash

## Package Management

- name: "Manage bash Packages"
  ansible.builtin.package:
    name: "{{ bash_package_names }}"
    state: "{{ bash_package_state }}"
  become: true
  tags:
    - "bash"
    - "package"

- name: "Manage bash scripting Packages"
  ansible.builtin.package:
    name: "{{ bash_script_package_names }}"
    state: "{{ bash_script_package_state }}"
  become: true
  tags:
    - "bash"
    - "package"
    - "development"

- name: "Manage bash powerline Packages"
  ansible.builtin.package:
    name: "{{ bash_powerline_package_names }}"
    state: "{{ bash_powerline_package_state }}"
  become: true
  tags:
    - "bash"
    - "powerline"
    - "package"

- name: "Manage bash Configuration"
  ansible.builtin.template:
    src: "wtd_bash.sh.j2"
    dest: "/etc/profile.d/wtd_bash.sh"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  when:
    - "bash_powerline_system_enabled | bool"
  tags:
    - "bash"
    - "powerline"
    - "package"
...
