---
# tasks/dependencies.yml for gnome_shell

- name: "Manage dependency Packages"
  ansible.builtin.package:
    name: "{{ gnome_shell_dependency_package_names }}"
    state: "{{ gnome_shell_dependency_package_state }}"
  become: true
  tags:
    - "gnome"
    - "shell"
    - "dependency"
    - "package"
...
