---
# tasks/mouse.yml for gnome_shell

- name: "Touchpad - Tap to Click"
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "{{ gnome_shell_touchpad_tap_to_click }}"
    state: "present"
  tags:
    - "gnome"
    - "shell"
    - "mouse"
    - "configuration"
...
