---
# roles/slack/tasks/main.yml

- name: "Manage slack Flatpaks"
  community.general.flatpak:
    name: "{{ slack_flatpak_names }}"
    state: "{{ slack_flatpak_state }}"
  tags:
    - "slack"
    - "flatpak"
...
