---
# tasks/main.yml for dnf

## Package Management

- name: "Manage dnf Packages"
  ansible.builtin.package:
    name: "{{ dnf_package_names }}"
    state: "{{ dnf_package_state }}"
  become: true
  tags:
    - "dnf"
    - "package"

## Configuration Management

- name: "Manage dnf Configuration"
  ansible.builtin.template:
    src: "dnf.conf.j2"
    dest: "/etc/dnf/dnf.conf"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  tags:
    - "dnf"
    - "configuration"
...
