---
# roles/thermald/tasks/main.yml

## Package Management

- name: "Manage thermald Packages"
  ansible.builtin.package:
    name: "{{ thermald_package_names }}"
    state: "{{ thermald_package_state }}"
  become: true
  tags:
    - "thermald"
    - "package"

## Service Management

- name: "Manage thermald Services"
  ansible.builtin.service:
    name: "{{ thermald_service_name }}"
    state: "{{ thermald_service_state }}"
    enabled: "{{ thermald_service_enabled }}"
  become: true
  tags:
    - "thermald"
    - "service"
...
