---
# tasks/main.yml for golang

## Package Management

- name: "Manage golang Packages"
  ansible.builtin.package:
    name: "{{ golang_package_names }}"
    state: "{{ golang_package_state }}"
  become: true
  tags:
    - "golang"
    - "package"
...
