---
# defaults/main.yml for update

## Package Management

update_package_enabled: true
update_package_names: "*"
update_package_state: "latest"

## System Management

update_reboot_confirm_enabled: true
update_reboot_remote_enabled: false
update_reboot_local_enabled: false
...
