---
# tasks/cpu.yml for misc

## Package Management

- name: "Manage thermald Packages"
  ansible.builtin.package:
    name: "thermald"
    state: "present"
  become: true
  tags:
    - "misc"
    - "cpu"
    - "package"

## Service Management

- name: "Manage thermald Service"
  ansible.builtin.service:
    name: "thermald.service"
    state: "started"
    enabled: true
  become: true
  tags:
    - "misc"
    - "cpu"
    - "service"
...
