---
# tasks/hostname.yml for misc

## Configuration Management

- name: "Manage hostname"
  ansible.builtin.hostname:
    name: "{{ misc_hostname }}"
  become: true
  tags:
    - "misc"
    - "hostname"
...
