---
# tasks/timezone.yml for misc

## Configuration Management

- name: "Manage timezone Configuration"
  community.general.timezone:
    name: "{{ misc_timezone }}"
  become: true
  tags:
    - "misc"
    - "timezone"
    - "configuration"
...
