---
# tasks/tools.yml for misc

## Package Management

- name: "Manage editor Packages"
  ansible.builtin.package:
    name: "{{ misc_editor_package_names }}"
    state: "present"
  become: true
  tags:
    - "misc"
    - "editor"
    - "package"

- name: "Manage other Packages"
  ansible.builtin.package:
    name: "{{ misc_other_package_names }}"
    state: "present"
  become: true
  tags:
    - "misc"
    - "other"
    - "package"

- name: "Manage utility Packages"
  ansible.builtin.package:
    name: "{{ misc_utility_package_names }}"
    state: "present"
  become: true
  tags:
    - "misc"
    - "utility"
    - "package"
...
