---
# ansible/playbooks/configure.yml

- name: "Configure Fedora Workstation"
  hosts: "localhost"
  connection: "local"

  vars_files:

    - "../manifest.yml"

  tasks:

    - name: "Include micro Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.desktop.micro"

    - name: "Include fedora_repos Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.desktop.fedora_repos"

    - name: "Include flathub_repos Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.desktop.flathub_repos"

    - name: "Include firefox Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.desktop.firefox"

    - name: "Include visualstudiocode Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.desktop.visualstudiocode"

    - name: "Include gpaste Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.desktop.gpaste"

    - name: "Include hadolint Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.desktop.hadolint"

    - name: "Include kubectl Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.desktop.kubectl"

    - name: "Include kubectx Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.desktop.kubectx"

    - name: "Include kubens Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.desktop.kubens"

    - name: "Include cirrus_cli Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.desktop.cirrus_cli"

    - name: "Include minikube Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.desktop.minikube"

    - name: "Include skaffold Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.desktop.skaffold"

    - name: "Include ngrok Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.desktop.ngrok"

#    - name: "Include gnome_config Role"
#      ansible.builtin.import_role:
#        name: "whiletruedoio.desktop.gnome_config"

    - name: "Include flatpak_apps Role"
      ansible.builtin.import_role:
        name: "whiletruedoio.desktop.flatpak_apps"
...
