---
# ansible/playbooks/update.yml

- name: "Configure Fedora Workstation"
  hosts: "localhost"
  connection: "local"

  vars_files:

    - "../manifest.yml"

  tasks:

    - name: "Import update Tasks"
      ansible.builtin.import_role:
        name: "update"
      tags:
        - "update"
        - "package"
...
