---
# roles/firefox/tasks/main.yml

- name: "Manage firefox Packages"
  ansible.builtin.package:
    name: "{{ firefox_package_names }}"
    state: "{{ firefox_package_state }}"
  become: true
  tags:
    - "firefox"
    - "package"

- name: "Manage firefox Flatpaks"
  community.general.flatpak:
    name: "{{ firefox_flatpak_names }}"
    state: "{{ firefox_flatpak_state }}"
  tags:
    - "firefox"
    - "flatpak"
...
