---
# tasks/main.yml for nodejs

## Package Management

- name: "Manage nodejs Packages"
  ansible.builtin.package:
    name: "{{ nodejs_package_names }}"
    state: "{{ nodejs_package_state }}"
  become: true
  tags:
    - "nodejs"
    - "package"
...
