---
# tasks/main.yml for vscode

## Repository Management

- name: "Manage vscode Repository Key"
  ansible.builtin.rpm_key:
    key: "{{ vscode_repository_key }}"
    state: "present"
  become: true
  tags:
    - "vscode"
    - "repository"

- name: "Manage vscode Repository"
  ansible.builtin.template:
    src: "vscode.repo.j2"
    dest: "/etc/yum.repos.d/vscode.repo"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  tags:
    - "vscode"
    - "repository"

## Package Management

- name: "Manage vscode Packages"
  ansible.builtin.package:
    name: "{{ vscode_package_names }}"
    state: "{{ vscode_package_state }}"
  become: true
  tags:
    - "vscode"
    - "package"

## Extension Management

- name: "Manage vscode Extensions"
  ansible.builtin.command:
    cmd: "code --install-extension {{ item }}"
  loop: "{{ vscode_extension_names }}"
  changed_when: false
  tags:
    - "vscode"
    - "extension"
...
