---
# defaults/main.yml for gnome_shell

## Dependency Management

gnome_shell_dependency_package_names:
  - "psutil"
  - "fedora-workstation-backgrounds"
gnome_shell_dependency_package_state: "present"

## Package Management

gnome_shell_unwanted_package_names:
  - "gnome-classic-session"
  - "gnome-shell-extension-background-logo"
  - "gnome-shell-extension-common"
  - "gnome-shell-extension-apps-menu"
  - "gnome-shell-extension-launch-new-instance"
  - "gnome-shell-extension-places-menu"
  - "gnome-shell-extension-window-list"
gnome_shell_unwanted_package_state: "absent"

## Configuration Management

gnome_shell_background_path: "/usr/share/backgrounds/gnome/adwaita-timed.xml"
gnome_shell_night_light_enabled: "true"
gnome_shell_night_light_schedule: "true"
gnome_shell_touchpad_tap_to_click: "true"
...
