---
# logitech/defaults/main.yml

- name: "Manage logitech Packages"
  ansible.builtin.package:
    name: "{{ logitech_package_names }}"
    state: "{{ logitech_package_state }}"
  become: true
  tags:
    - "logitech"
    - "package"

- name: "Manage logitech Flatpaks"
  community.general.flatpak:
    name: "{{ logitech_flatpak_names }}"
    state: "{{ logitech_flatak_state }}"
  become: true
  tags:
    - "logitech"
    - "flatpak"
...
