---
# tasks/main.yml for flathub

## Dependency Management

- name: "Manage flathub Dependencies"
  ansible.builtin.package:
    name: "{{ flathub_dependency_package_names }}"
    state: "{{ flathub_dependency_package_state }}"
  become: true
  tags:
    - "flathub"
    - "dependency"
    - "package"

## Repository Management

- name: "Manage flathub Repository"
  community.general.flatpak_remote:
    name: "{{ flathub_repository_name }}"
    state: "{{ flathub_repository_state }}"
    flatpakrepo_url: "{{ flathub_repository_url }}"
    method: "{{ flathub_repository_method }}"
  become: true
  tags:
    - "flathub"
    - "repository"
...
