---
# tasks/main.yml for podman

## Package Management

- name: "Manage podman Packages"
  ansible.builtin.package:
    name: "{{ podman_package_names }}"
    state: "{{ podman_package_state }}"
  become: true
  tags:
    - "podman"
    - "package"

## Service Management

- name: "Manage podman Socket"
  ansible.builtin.service:
    name: "{{ podman_socket_name }}"
    state: "{{ podman_socket_state }}"
    enabled: "{{ podman_socket_enabled }}"
  become: true
  tags:
    - "podman"
    - "service"

- name: "Manage podman-auto-update Timer"
  ansible.builtin.service:
    name: "{{ podman_auto_update_timer_name }}"
    enabled: "{{ podman_auto_update_timer_enabled }}"
  become: true
  tags:
    - "podman"
    - "service"

- name: "Manage podman-restart Service"
  ansible.builtin.service:
    name: "{{ podman_restart_service_name }}"
    enabled: "{{ podman_restart_service_enabled }}"
  become: true
  tags:
    - "podman"
    - "service"
...
