---
# tasks/main.yml for selinux

## Package Management

- name: "Manage selinux Packages"
  ansible.builtin.package:
    name: "{{ selinux_package_names }}"
    state: "{{ selinux_package_state }}"
  become: true
  tags:
    - "selinux"
    - "package"

## Configuration Management

- name: "Manage selinux Configuration"
  ansible.posix.selinux:
    policy: "{{ selinux_config_policy }}"
    state: "{{ selinux_config_state }}"
  become: true
  tags:
    - "selinux"
    - "configuration"
...
