---
# defaults/main.yml for podman

## Package Management

podman_package_names:
  - "podman"
  - "podman-compose"
  - "podman-docker"
  - "podman-remote"
podman_package_state: "present"

## Service Management

podman_socket_name: "podman.socket"
podman_socket_state: "started"
podman_socket_enabled: true

podman_auto_update_timer_name: "podman-auto-update.timer"
podman_auto_update_timer_enabled: true

podman_restart_service_name: "podman-restart.service"
podman_restart_service_enabled: true
...
