---
# ansible playbook for github.com/dschier-wtd/fedora-workstation

- name: "Configure Fedora Workstation"
  hosts: "localhost"
  connection: "local"

  tasks:

    - name: "Import update Tasks"
      ansible.builtin.import_role:
        name: "update"
...
