---
# tasks/main.yml for update

## Package Management

- name: "Manage package Updates"
  ansible.builtin.package:
    name: "{{ update_package_names }}"
    state: "{{ update_package_state }}"
  become: true
  when:
    - "update_package_enabled | bool"
  notify: "Reboot System"
  tags:
    - "update"
    - "package"
...
