---
# tasks/main.yml for gnome_applications

## Package Management

- name: "Remove unwanted application Packages"
  ansible.builtin.package:
    name: "{{ gnome_app_unwanted_package_names }}"
    state: "{{ gnome_app_unwanted_package_state }}"
  become: true
  tags:
    - "gnome"
    - "removal"
    - "flatpak"

- name: "Manage media Packages"
  ansible.builtin.package:
    name: "{{ gnome_app_media_package_names }}"
    state: "{{ gnome_app_media_package_state }}"
  become: true
  tags:
    - "gnome"
    - "media"
    - "package"

- name: "Manage system Packages"
  ansible.builtin.package:
    name: "{{ gnome_app_system_package_names }}"
    state: "{{ gnome_app_system_package_state }}"
  become: true
  tags:
    - "gnome"
    - "system"
    - "package"

## Flatpak Management

- name: "Manage gnome cloud flatpaks"
  community.general.flatpak:
    name: "{{ gnome_app_cloud_flatpak_names }}"
    state: "{{ gnome_app_cloud_flatpak_state }}"
  tags:
    - "gnome"
    - "cloud"
    - "flatpak"

- name: "Manage gnome development flatpaks"
  community.general.flatpak:
    name: "{{ gnome_app_development_flatpak_names }}"
    state: "{{ gnome_app_development_flatpak_state }}"
  tags:
    - "gnome"
    - "development"
    - "flatpak"

- name: "Manage gnome gaming flatpaks"
  community.general.flatpak:
    name: "{{ gnome_app_gaming_flatpak_names }}"
    state: "{{ gnome_app_gaming_flatpak_state }}"
  when:
    - "gnome_app_gaming_flatpak_state != 'ignore'"
  tags:
    - "gnome"
    - "gaming"
    - "flatpak"

- name: "Manage gnome grahic flatpaks"
  community.general.flatpak:
    name: "{{ gnome_app_graphic_flatpak_names }}"
    state: "{{ gnome_app_graphic_flatpak_state }}"
  tags:
    - "gnome"
    - "graphic"
    - "flatpak"

- name: "Manage gnome media flatpaks"
  community.general.flatpak:
    name: "{{ gnome_app_media_flatpak_names }}"
    state: "{{ gnome_app_media_flatpak_state }}"
  tags:
    - "gnome"
    - "media"
    - "flatpak"

- name: "Manage gnome messaging flatpaks"
  community.general.flatpak:
    name: "{{ gnome_app_messaging_flatpak_names }}"
    state: "{{ gnome_app_messaging_flatpak_state }}"
  tags:
    - "gnome"
    - "messaging"
    - "flatpak"

- name: "Manage gnome productivity flatpaks"
  community.general.flatpak:
    name: "{{ gnome_app_productivity_flatpak_names }}"
    state: "{{ gnome_app_productivity_flatpak_state }}"
  tags:
    - "gnome"
    - "production"
    - "flatpak"

- name: "Manage gnome secret flatpaks"
  community.general.flatpak:
    name: "{{ gnome_app_secret_flatpak_names }}"
    state: "{{ gnome_app_secret_flatpak_state }}"
  tags:
    - "gnome"
    - "secret"
    - "flatpak"

- name: "Manage gnome system flatpaks"
  community.general.flatpak:
    name: "{{ gnome_app_system_flatpak_names }}"
    state: "{{ gnome_app_system_flatpak_state }}"
  tags:
    - "gnome"
    - "secret"
    - "flatpak"

- name: "Manage gnome utility flatpaks"
  community.general.flatpak:
    name: "{{ gnome_app_utility_flatpak_names }}"
    state: "{{ gnome_app_utility_flatpak_state }}"
  tags:
    - "gnome"
    - "utility"
    - "flatpak"
...
