---
# tasks/main.yml for gnome_applications

## Package Management

- name: "Remove unwanted application Packages"
  ansible.builtin.package:
    name: "{{ gnome_app_unwanted_package_names }}"
    state: "{{ gnome_app_unwanted_package_state }}"
  become: true
  tags:
    - "gnome"
    - "removal"
    - "package"

- name: "Manage gnome cloud Packages"
  community.general.flatpak:
    name: "{{ gnome_app_cloud_package_names }}"
    state: "{{ gnome_app_cloud_package_state }}"
  become: true
  tags:
    - "gnome"
    - "cloud"
    - "package"
    - "flatpak"

- name: "Manage gnome development Packages"
  community.general.flatpak:
    name: "{{ gnome_app_development_package_names }}"
    state: "{{ gnome_app_development_package_state }}"
  become: true
  tags:
    - "gnome"
    - "development"
    - "package"
    - "flatpak"

- name: "Manage gnome gaming Packages"
  community.general.flatpak:
    name: "{{ gnome_app_gaming_package_names }}"
    state: "{{ gnome_app_gaming_package_state }}"
  become: true
  tags:
    - "gnome"
    - "gaming"
    - "package"
    - "flatpak"

- name: "Manage gnome grahics Packages"
  community.general.flatpak:
    name: "{{ gnome_app_graphics_package_names }}"
    state: "{{ gnome_app_graphics_package_state }}"
  become: true
  tags:
    - "gnome"
    - "graphics"
    - "package"
    - "flatpak"

- name: "Manage gnome media Packages"
  community.general.flatpak:
    name: "{{ gnome_app_media_package_names }}"
    state: "{{ gnome_app_media_package_state }}"
  become: true
  tags:
    - "gnome"
    - "media"
    - "package"
    - "flatpak"

- name: "Manage gnome messaging Packages"
  community.general.flatpak:
    name: "{{ gnome_app_messaging_package_names }}"
    state: "{{ gnome_app_messaging_package_state }}"
  become: true
  tags:
    - "gnome"
    - "messaging"
    - "package"
    - "flatpak"

- name: "Manage gnome productivity Packages"
  community.general.flatpak:
    name: "{{ gnome_app_productivity_package_names }}"
    state: "{{ gnome_app_productivity_package_state }}"
  become: true
  tags:
    - "gnome"
    - "production"
    - "package"
    - "flatpak"

- name: "Manage gnome secret Packages"
  community.general.flatpak:
    name: "{{ gnome_app_secret_package_names }}"
    state: "{{ gnome_app_secret_package_state }}"
  become: true
  tags:
    - "gnome"
    - "secret"
    - "package"
    - "flatpak"

- name: "Manage gnome system Packages"
  community.general.flatpak:
    name: "{{ gnome_app_system_package_names }}"
    state: "{{ gnome_app_system_package_state }}"
  become: true
  tags:
    - "gnome"
    - "secret"
    - "package"
    - "flatpak"

- name: "Manage gnome utility Packages"
  community.general.flatpak:
    name: "{{ gnome_utility_package_names }}"
    state: "{{ gnome_utility_package_state }}"
  become: true
  tags:
    - "gnome"
    - "utility"
    - "package"
    - "flatpak"
...
