---
# tasks/main.yml for firewalld

## Package Management

- name: "Manage firewalld Packages"
  ansible.builtin.package:
    name: "{{ firewalld_package_names }}"
    state: "{{ firewalld_package_state }}"
  become: true
  tags:
    - "firewalld"
    - "package"

## Service Management

- name: "Manage firewalld Services"
  ansible.builtin.service:
    name: "{{ firewalld_service_name }}"
    state: "{{ firewalld_service_state }}"
    enabled: "{{ firewalld_service_enabled }}"
  become: true
  tags:
    - "firewalld"
    - "service"
...
